### ISSUE TITLE
[cli] Extend scaffolded init app

### ISSUE THREAD

**Issue by brillout** [reframejs/reframe#10]
Could be nice to have the init app have two pages that link each other.

We could also add CSS and async data fetching.

The init app would then cover the "CSS & Static Assets", "Async Data", and "Links & Page Navigation" sections of the the usage manual.

It would then feel like a real app.

@tdfranklin What do you think?

**Comment by tdfranklin** [comment]
Yes!  That's exactly where I wanted to get to!  Sort of how when you run `create-react-app myApp` then you cd into the app and start the server, it loads a nice little page on localhost that basically say's `Hello from React` or something like that.  I think we should have a similar setup.  That's what I was trying to go for with the homePage and homeView setup, but don't think it's quite there yet.

**Comment by brillout** [comment]
Done
Good job @tdfranklin
