### ISSUE TITLE
[cli] show help when running `reframe`

### ISSUE THREAD

**Issue by brillout** [reframejs/reframe#21]
Basically doing `reframe` would be the same than doing `reframe -h`.
@tdfranklin Not sure if that's possible with `commander`?

**Comment by brillout** [comment]
@tdfranklin If it's not easily possible then let's just drop this. It's clearly not high-prio

**Comment by tdfranklin** [comment]
Hrm... I don't believe this is possible with commander, but I will investigate and get back to you.

**Comment by tdfranklin** [comment]
I stand corrected - PR submitted.

**Comment by brillout** [comment]
done
