### ISSUE TITLE
Move init code to a new plugin `@reframe/init`

### ISSUE THREAD

**Issue by brillout** [reframejs/reframe#23]
I've made that plugins can be dynamically added;

```js
const projectConfig = getProjectConfig();

projectConfig.addPlugin(
   startCommands()
);
```

Note that `getProjectConfig` should now be used instead of `processReframeConfig`.
And `projectConfig` is the pendant of `reframeConfig._processed`.
E.g. `projectConfig.cli_commands` will include all cli commands added by plugins.

`addPlugin` usage example:
https://github.com/reframejs/reframe/blob/master/helpers/cli/cli.js#L23-L25

We could now move all scaffold code and the `init` commad a new plugin `@reframe/init`

@tdfranklin what do you think?

**Comment by brillout** [comment]
We can make that the CLI loads the plugin. That way, the plugin is always included with the CLI. Similar to how `startCommands` is always included with the CLI

**Comment by tdfranklin** [comment]
I'll ask on here as well as Discord.  So, are you wanting this to be it's own package under the plugin directory (like cli-plugins, default-kit, react-router, etc) or are you wanting this to just be another file under reframe/helpers/cli that looks like startCommands() only passes all the init/scaffolding info?
