### ISSUE TITLE
React-Native-Web

### ISSUE THREAD

**Issue by gHashTag** [reframejs/reframe#29]
I tried to connect the library  [**react-native-web**](https://github.com/necolas/react-native-web#installation) to the project, but found this error in response. 

```Module not found: Error: Can't resolve 'react-native' in '...reframe/views/Masters'```

If such an opportunity?

**Comment by brillout** [comment]
Sounds like it's not installed? Is it present under your `node_modules/` directory?

Yes you can use `react-native-web` with Reframe. If it's something you'd be up to we could create a `@reframe/react-native-web` plugin together. Using `react-native-web` would then simply be a matter of using the plugin.

Let me know when you want to use `react-native-web` with Reframe and I'll let you know how to do it. It's fairly easy to do.

**Comment by gHashTag** [comment]
I'm ready, but I do not know if I'll get it =)

**Comment by brillout** [comment]
We'll be fine, you'll see ;-)

But if you don't have time I'll just write the plugin myself. Entirely up to you =)

**Comment by gHashTag** [comment]
This library helps me write less code for the web and mobile =)
Especially to be engaged in Animation with one powerful tool.
I'll wait with impatience!

**Comment by brillout** [comment]
Implemented
