### ISSUE TITLE
restart dev server

### ISSUE THREAD

**Issue by gHashTag** [reframejs/reframe#30]
In the event of an error, you must restart the server each time. 
```
reframe start
error
reframe start
error
...
```
It's just me and this is normal behavior? It would be cool something like nodemon.

**Comment by brillout** [comment]
That shouldn't be the case.

Feel free to point me to a repo and a specific commit and how you get to that situation. I'll then look into it.

**Comment by gHashTag** [comment]
[Source code](https://github.com/gHashTag/reframe)

**Comment by brillout** [comment]
Just tried your latest commit and added an error and fixed it. Worked as expected: The error was shown in the console and when fixed the app was re-built and the browser automatically reloaded. The server didn't crash and I hadn't to restart it.

What's your error that causes the server to crash?

**Comment by brillout** [comment]
Ok got one that crashes the server `ReferenceError: window is not defined`. I know why it does it. I'll think about a fix. So yes for now for these type of errors you'll need to restart the server. I'll let you know when I implemented a fix.

**Comment by brillout** [comment]
This is fixed.

There still some edge cases left where the server needs to be manually restarted. But closing for now.
