### ISSUE TITLE
window.innerWidth or window.innerHeight

### ISSUE THREAD

**Issue by gHashTag** [reframejs/reframe#31]
What to use to determine the height and width of the browser screen?
In the case of
`const w = window.innerWidth`
this error appears
`ReferenceError: window is not defined`
How do I get to the window object?

**Comment by brillout** [comment]
That's because of SSR: Your views are run both in the browser and on Node.js.

Just do `if( typeof window !== "undefined ) { const w = window.innerWidth; /* etc. */ }` to check whether your view is being run on Node.js or in the browser.

Does that make sense?

**Comment by gHashTag** [comment]
I actively develop mobile applications on the react native and I would not like to write two codes, one for mobile platforms and the other for web. [Сomponent Dimention solves this problem.](http://necolas.github.io/react-native-web/storybook/?selectedKind=APIs&selectedStory=Dimensions&full=0&addons=0&stories=1&panelRight=0)

**Comment by brillout** [comment]
The thing is that the Node.js server cannot know the size of the browser. The server simply doesn't have that information.

But you can do that
```js

function isNodejs() {
    return typeof window === "undefined";
}

const platform = (x) => {
  if( isNodejs() ) {
    return x * 3.9;
  }
  try {
    const w = window.innerWidth
    if (w <= 320) {
      return x + 3 //'iphone5'
    } else if (w <= 375 && w > 321) {
      return x * 3.7 // 'iphone6'
    } else if (w <= 414 && w > 375) {
      return x * 3.9 // 'iphone6+'
    } else if (w > 414) {
      return x * 3.9 // 'web'
    }
  } catch (e) {
    throw e
  }
}
```

In other words:
 - When the view is rendered to the DOM in the browser the platform function is run as normal
 - When the view is rendered to HTML on the server then the platform function returns `x * 3.9`

**Comment by gHashTag** [comment]
Awesome!!!
