### ISSUE TITLE
Main border

### ISSUE THREAD

**Issue by gHashTag** [reframejs/reframe#32]
I'm implementing a menu from the library react-burger-menu, аnd when the menu is activated, a 8-pixel border is displayed.

![border mov](https://user-images.githubusercontent.com/6774813/39662798-15174b9c-5070-11e8-92b6-6a908b69dd6b.gif)

In the CRA, I did not have it. How can I remove it?

**Comment by brillout** [comment]
That's because by default the browser sets some margin to the body. If I remember correctly adding the CSS `body {margin: 0px}` should do the trick. Let me know if it works.

**Comment by gHashTag** [comment]
yes! working!!!
