### ISSUE TITLE
Rename the framework

### ISSUE THREAD

**Issue by hkjels** [reframejs/reframe#37]
There's already a web-framework called `Re-frame`, you should rebrand before marketing your framework any further.

**Comment by brillout** [comment]
To me it's ok to have two projects with similar names.

We already talked about it here https://github.com/reframejs/reframe/issues/1.

Feel free to object to my opinion.

**Comment by mike-thompson-day8** [comment]
Oh sure, nothing to worry about at all, assuming you don't care at all about the confusion you might cause others.

**Comment by hkjels** [comment]
The choice of name is not an issue; it's actually two issues, as you yourself point out. And that's of a grand total of 22 closed issues 🤔. I believe you should give this some more thought

**Comment by brillout** [comment]
@mike-thompson-day8 @hkjels 

I'm thinking of renaming the project but it's quite painful to me since the name "Reframe" fits *perfectly* the vision of what I'm trying to achieve.

As @dannyfreeman pointed out:

> I was telling a friend about the clojurescript framework, re-frame. After our conversation he went to do some research on re-frame and got thrown for a loop when he found this repository.

I see this to be a *concrete problem*. So maybe a solution would be to add a link to re-frame on Reframe's readme. That would solve this *concrete situation*.

What do you think?

**Comment by brillout** [comment]
@mike-thompson-day8 @hkjels @dannyfreeman Thoughts on this? If you absolutely persist then I will rename the project.

But I would find it best if we can have a conversation about concrete implications of two frameworks having the same name while living in different ecosystems. This would definitely help me: having a rationale would make it less painful for me to rename.

**Comment by dannyfreeman** [comment]
I still think a rename would still be a good idea, but understand the hesitation (finding a good name is really hard). At the very least linking to the clojurescript re-frame project (https://day8.github.io/re-frame/) in the readme might help alleviate the confusion when people stumble upon this when looking for the other.

**Comment by brillout** [comment]
@dannyfreeman Thanks you for your answer.

I'm thinking of new name, but it's not easy

Yes I know, it would be great have a "official" discussion @mike-thompson-day8 @superstructor @danielcompton

It would help me to have discussion about *concrete* implications

In the meantime I added this note on the top of the readme:
> (Unrelated to ClojureScript's [re-frame](https://github.com/day8/re-frame).)

**Comment by brillout** [comment]
@mike-thompson-day8 @superstructor @danielcompton any luck? It'd be great to have this conversation so we can resolve this dispute and bury the hatchet. The longer we delay the conversation, the more will it be painful for me to rename Reframe to something else.

**Comment by superstructor** [comment]
@brillout This is the first and last time I'll engage on this issue. 

There is no hatchet, there is just you repeatedly asking for approval for a bad idea. That approval will not come. You should have solved this in February 2018 by renaming the project. The only person who has delayed this is you. There have been so many issues raised by different people, #1, #58, #46... how can you not see this as an issue ? 

If I was building a new database, I would not call it 'PostgreSQL'. Putting trademark issues aside, it would just confuse people and cause an inordinate amount of wasted time for developers searching for related news, tutorials, examples, bugs, extensions on Google, StackOverflow, Reddit etc.

If you [search on Google for 're-frame site:github.com'](https://letmegooglethat.com/?q=site%3Agithub.com+re-frame) there are over 215,000 results almost all exclusively for ClojureScript re-frame.

You also can't say 'they live in different worlds'. ClojureScript is JavaScript. It compiles to JS. It uses the same libraries (e.g. React). It uses the same tools. It achieves the same use cases. It runs on the same platforms (web browsers, isomorphic etc).

[**ClojureScript re-frame does do isomorphic React apps**](https://techascent.com/blog/isomorphic-rendering.html). In fact, the entire codebase is `.cljc` which can be run on a Java Virtual Machine or Node.js or a web browser!

Even if you do not care about causing ClojureScript users inconvenience, why would you force your own users to shift through all that noise ? If you care about your users' time, then give them a unique-enough name to search for when they need help.

Lets say conservatively ClojureScript re-frame has ~5000 developers using it regularly. Now lets say you muddy the waters enough in search results to waste just 1 single minute of those developers' time each workday. That is wasting 2.5 person years every year! (assuming 262 workdays).

**Comment by mike-thompson-day8** [comment]
@brillout 
Thank you for putting the redirect note at the top of your README.  That will help people.
 
But as @superstructor has firmly pointed out, this is a problem you created, despite multiple people clearly warning you it would cause pain. Please don't continue to ping us trying to engage us in a discussion to resolve a problem you stubbornly created, and only you can solve.  The ability to fix this continues to be in your hands. Over to you.  Please don't @ me.

**Comment by brillout** [comment]
I can see Google search result conflicts to be a considerable drawback for both re-frame and Reframe users. I decided to rename the project.
