### ISSUE TITLE
Deploying with Up

### ISSUE THREAD

**Issue by AurelienLourot** [reframejs/reframe#38]
I'd like to extend Reframe so that the user only needs to follow these steps:

1. (outside of Reframe) In the AWS web console, create a user and an access key. Attach the `IAMFullAccess` policy to the user. (Can be skipped by people already using AWS)

2. `reframe aws configure <access-key-id> <secret-access-key> <region>` creates `~/.aws/config` and `~/.aws/credentials`. (Can be skipped by people already using AWS)

3. `reframe eject up-iam-policy` creates `up/iam-policy.json` so that the user can modify it. (Might be an overkill as we don't even need that for ghuser.io)

4. `reframe up setup-iam <aws-username>` creates the IAM policy and group and puts `<aws-username>` into the group.

5. `reframe up init` downloads `up/up` and creates `up/up.json`.

6. `reframe up deploy` puts the app online. (We need a few warnings here and there saying that we're not responsible for the resulting AWS costs)

7. `reframe up undeploy` destroys all the AWS resources set up by the previous step.

What do you think @brillout?

**Comment by brillout** [comment]
Love it so much ❤️ 
Would be so cool. But I guess you'd rather work for ghuser atm:)

**Comment by brillout** [comment]
Closing because I'm leaning more towards auto deploy to a stateful server, such as AWS EC2. I don't expect to support auto deploy to serverless anytime soon. I'll be updating Reframe's auto deploy plans at https://github.com/reframejs/reframe/issues/42.

@AurelienLourot Thanks a lot for your contribution back then
