### ISSUE TITLE
Convert to TypeScript

### ISSUE THREAD

**Issue by aleclarson** [reframejs/reframe#44]
Hello! What are your feelings on this?

**Comment by brillout** [comment]
Hi!

Yes it would make a lot of sense for TypeScript users to eject TypeScript code.

On the other hand it would force non-TypeScript users to use and learn TypeScript for ejected code.

Right now it's not clear to me whether to convert or not. I'd rather gather further users and insights before taking that decision.

**Comment by brillout** [comment]
Hello @aleclarson !

It's now super easy to create a starter.

Reframe is now merely a collection of libraries and starters, creating a starter is now only a matter of creating a boilerplate that uses [ssr-coin](https://github.com/reframejs/ssr-coin) and [Wildcard](https://github.com/reframejs/wildcard-api).

Reframe starters are simply git repos and using a Reframe starter is only a matter of doing `git clone`.

Up for creating a TypeScript starter together?!:-)

**Comment by brillout** [comment]
I'm adding TypeScript everywhere.
 - https://github.com/reframejs/wildcard-api already uses TypeScript.
 - https://github.com/reframejs/goldpage/issues/24 will be rewritten in TypeScript
