### ISSUE TITLE
CSS modules support?

### ISSUE THREAD

**Issue by alishahlakhani** [reframejs/reframe#47]
Are there any plans to support CSS modules support to the library. I connected my codebase to your library but the problem is that all the .module.scss files are now not working. I believe this is because 'react-scripts' complies CSS modules but your lib does not. Is that a possible goal for future?

**Comment by brillout** [comment]
Yes it is. I can implement a plugin for it the next couple of days. We can also implement it together if that's a thing that would interest you.

I'm curious, why SCSS and not PostCSS?

**Comment by alishahlakhani** [comment]
To be honest, I've never worked with PostCSS or with this low level codes.
I would love to learn, if you can guide. 👍

**Comment by brillout** [comment]
The document is good https://postcss.org

You can then use the PostCSS plugin https://github.com/reframejs/reframe/tree/master/plugins/postcss
