### ISSUE TITLE
[cli] global config -- "always use yarn"

### ISSUE THREAD

**Issue by aleclarson** [reframejs/reframe#48]
This is a feature proposal. (unless this already exists?)

Something like `.npmrc` for Reframe.

Then an option like `npm: "yarn"` in there.

Sorry if this is a duplicate.

**Comment by brillout** [comment]
Reframe only installs packages when doing `reframe create react-frontend`. When doing so Reframe doesn't add any `package-lock.json` nor `yarn.lock`; it doesn't assume whether you use yarn or npm.

Once you've scaffolded your app, Reframe doesn't install packages anymore.

In a nutshell: Reframe is npm/yarn agnostic and can be used with both.

**Comment by brillout** [comment]
Does that make sense?

**Comment by aleclarson** [comment]
Yeah thanks. I don't remember what made me think this was necessary. Something in the docs may have mislead me (not sure).

**Comment by brillout** [comment]
Ok. Let me know when the docs are not clear and I'll improve them.
