### ISSUE TITLE
Custom / Private starters

### ISSUE THREAD

**Issue by freeman** [reframejs/reframe#53]
It seems currently the only starters supported are in-tree (in the `create` plugin). 

Am I correct ? If so is supporting private starters (as an npm package for example) be something this project would like to cover ?

Reframe looks great by the way :)

**Comment by brillout** [comment]
> It seems currently the only starters supported are in-tree (in the `create` plugin).
> 
> Am I correct ? 

yes

> If so is supporting private starters (as an npm package for example) be something this project would like to cover ?

This would be out of scope for Reframe.

That said Reframe is built on top of do-one-thing-do-it-well libraries I wrote / the community wrote. You can create any boilerplate you want on top of these DOTDITW libraries. These libraries are all super flexible so you can build any kind of boilerplate you want.

What should your boilerplate be able to do? We can design your boikerplate together if you want.

> Reframe looks great by the way :)

Thanks :)

**Comment by freeman** [comment]
The private starters would be mainly to include private packages we use in my org, so they would not benefit the community. I'd like also to enable typescript support by default. 

So I guess my main option is to create a private fork of `create` and `cli` ?

**Comment by brillout** [comment]
The easiest would be:
 1. Scaffold an app with `$ reframe create react-app` / `$ reframe create react-frontend` / `$ reframe create react-sql`.
2. Add your private packages and the Reframe typescript plugin to the app.
3. Published the modified app to a private repo `git@github.com:your-private-org/reframe-boilerplate`.
4. New projects would start off this boilerplate.

**Comment by brillout** [comment]
Now that Reframe is merely a collection of libraries and starters, creating a starter is now only a matter of creating a boilerplate that uses [ssr-coin](https://github.com/reframejs/ssr-coin) and [Wildcard](https://github.com/reframejs/wildcard-api).

Reframe starters are now simply git repos and using a Reframe starter is only a matter of doing `git clone`.
