### ISSUE TITLE
Consider changing the name of this framework

### ISSUE THREAD

**Issue by dannyfreeman** [reframejs/reframe#58]
I was telling a friend about the clojurescript framework, re-frame. After our conversation he went to do some research on re-frame and got thrown for a loop when he found this repository. You should really consider changing the name to help avoid confusion with the original re-frame framework. In addition to that, there is an implementation of the clojurescript framework done in javascript called reframejs: http://karolmajta.github.io/reframe-js/ that confuses things even further.

I know others have suggested this, but it seems to be a recurring problem.

**Comment by brillout** [comment]
> After our conversation he went to do some research on re-frame and got thrown for a loop when he found this repository

Interesting use case and I'd be curious to know exactly what was going on in his head?

If the same name confused him for 30 seconds, that's not cool for sure, but it's not *that* bad.

So far, this whole topic of "re-frame" and "reframe" having the same name seemed a bit too nitpicky from my perspective.
